# Dataset 1 - Aplliances Energy Prediction (UCI)

Tratamento básico de colunas, valores em branco e redução da amostra para 10%:

![Tratamento_de_dados_selecao_colunas_img.svg]()

In [ ]:
import pandas as pd

In [ ]:
# Carregar os dados externos do arquivo .csv
dados = pd.read_csv('DADOS_TRATADOS_01.csv', sep=',')

In [ ]:
# Início da Análise Exploratória, para começar a trabalhar com dataframes, analisar suas propriedades e ver se bate com o esperado

## 1.

In [ ]:
# visualizar os primeiros registros
dados.head()

   Appliances  lights     T1     RH_1       T2     RH_2       T3     RH_3
0          50       0  22.73  41.2000  19.8567  45.4667  24.3567  38.7900
1          70      10  25.10  32.6333  27.2720  26.8500  25.0000  36.2900
2          50       0  21.00  37.7600  18.5667  38.9633  21.1000  35.2000
3          50       0  21.70  42.0000  18.7900  45.7900  23.6000  39.4000
4          50       0  22.89  39.2900  20.7720  39.7000  24.4371  37.5643

In [ ]:
# Verificar as dimensões do dataframe
dados.shape

(1974, 8)

In [ ]:
# Verificar o formato dos dados
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1974 entries, 0 to 1973
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Appliances  1974 non-null   int64
 1   lights      1974 non-null   int64
 2   T1          1974 non-null   float64
 3   RH_1        1974 non-null   float64
 4   T2          1974 non-null   float64
 5   RH_2        1974 non-null   float64
 6   T3          1974 non-null   float64
 7   RH_3        1974 non-null   float64
dtypes: float64(6), int64(2)
memory usage: 123.5 KB

## 2.

In [ ]:
# Verificar estatísticas descritivas das colunas numéricas
dados.describe()

,Appliances,lights,T1,RH_1,T2,RH_2,T3,RH_3
count,1974.000000,1974.000000,1974.000000,1974.000000,1974.000000,1974.000000,1974.000000,1974.000000
mean,96.990881,3.738602,21.605782,40.171571,20.243204,40.357593,22.181304,39.153457
std,101.903639,7.902380,1.613666,3.996103,2.199323,4.145257,1.982891,3.263119
min,10.000000,0.000000,16.790000,28.193300,16.100000,24.596700,17.290000,28.860000
25%,50.000000,0.000000,20.600000,37.328350,18.700000,37.707500,20.700000,36.790000
50%,60.000000,0.000000,21.500000,39.500000,19.790000,40.326700,22.033300,38.500000
75%,100.000000,0.000000,22.524975,42.890825,21.390000,43.230000,23.200000,41.590000
max,1080.000000,50.000000,26.100000,57.395000,29.133300,54.656700,29.160000,48.026700

In [ ]:
dados.columns

Index(['Appliances', 'lights', 'T1', 'RH_1', 'T2', 'RH_2', 'T3', 'RH_3'], dtype='object')

In [ ]:
# renomear todas as colunas do df original "dados"
dados = dados.rename(columns={'Appliances': 'Consumo_Eletrodomesticos',
                              'RH_1': 'RH1',
                              'RH_2': 'RH2',
                              'RH_3': 'RH3'
                              })
dados.head()

,Consumo_Eletrodomesticos,lights,T1,RH1,T2,RH2,T3,RH3
0,50,0,22.73,41.2000,19.8567,45.4667,24.3567,38.7900
1,70,10,25.10,32.6333,27.2720,26.8500,25.0000,36.2900
2,50,0,21.00,37.7600,18.5667,38.9633,21.1000,35.2000
3,50,0,21.70,42.0000,18.7900,45.7900,23.6000,39.4000
4,50,0,22.89,39.2900,20.7720,39.7000,24.4371,37.5643

In [ ]:
maior_consumo = dados['Consumo_Eletrodomesticos'].max()
maior_consumo

1080

In [ ]:
limiar_70 = maior_consumo * 0.7
limiar_70

756.0

In [ ]:
df_filtrado = dados[dados['Consumo_Eletrodomesticos'] >= limiar_70]
df_filtrado.head()

,Consumo_Eletrodomesticos,lights,T1,RH1,T2,RH2,T3,RH3
17,890,20,19.7300,37.8633,18.5667,34.09,18.39,36.8633
288,770,0,22.8233,48.7633,22.3900,39.80,23.29,39.2300
1255,1080,30,21.9300,42.7667,21.0400,38.08,20.70,40.6333

In [ ]:
total_selecionados = len(df_filtrado)

total_original = len(dados)
percentual = (total_selecionados / total_original) * 100

print(f"Registros selecionados: {total_selecionados}")
print(f"Percentual da amostra: {percentual:.2f}%")

Registros selecionados: 3
Percentual da amostra: 0.15%

In [ ]:
# Calcule a temperatura média de T1.
media_T1 = dados['T1'].mean()
print(f" {media_T1:.2f}")

 21.61

In [ ]:
# Crie outro DataFrame contendo simultaneamente consumo acima de 70% do máximo e temperatura acima da média.

df_limiar70_e_mediaT1 = dados[
    (dados['Consumo_Eletrodomesticos'] > limiar_70) &
    (dados['T1'] > media_T1)
]
df_limiar70_e_mediaT1.head()

,Consumo_Eletrodomesticos,lights,T1,RH1,T2,RH2,T3,RH3
288,770,0,22.8233,48.7633,22.39,39.80,23.29,39.2300
1255,1080,30,21.9300,42.7667,21.04,38.08,20.70,40.6333

In [1]:
# Compare os dois DataFrames e explique o efeito da inclusão da temperatura como segundo critério.
print('A inclusão de temperatura como segundo critério limitou ainda mais os registros acima da limiar 70%,\na condicional "E" tirou mais 1 registro por não estar acima da média de T1.')

A inclusão de temperatura como segundo critério limitou ainda mais os registros acima da limiar 70%,
a condicional "E" tirou mais 1 registro por não estar acima da média de T1.